In [2]:
import numpy as np

In [19]:
u = np.array([2,4,5,6])
u

array([2, 4, 5, 6])

In [20]:
#Vectors operation
v = np.array([1,0,0,2])
v

array([1, 0, 0, 2])

In [8]:
u+v

array([3, 4, 5, 8])

In [9]:
2*u

array([ 4,  8, 10, 12])

In [11]:
u*v

array([ 2,  0,  0, 12])

In [5]:
#MULTIPLICATION
u.shape

(4,)

In [6]:
v.shape[0]

4

In [21]:
def vector_vector_miltiplication(u, v):
    assert u.shape[0] == v.shape[0]
    n = u.shape[0]
    result = 0.0
    for i in range(n):
        result = result + u[i] * v[i]
        return result
        

In [22]:
vector_vector_miltiplication(u, v)

np.float64(2.0)

In [9]:
u.dot(v)

np.int64(14)

In [29]:
U = np.array([
    [2,4,5,6],
    [1,2,1,2],
    [3,1,2,1]
])
U

array([[2, 4, 5, 6],
       [1, 2, 1, 2],
       [3, 1, 2, 1]])

In [30]:
U.shape

(3, 4)

In [31]:
v = np.array([1,0.5,2,1])
v

array([1. , 0.5, 2. , 1. ])

In [32]:
def matrix_vector_multiplication(U,v):
    assert U.shape[1] == v.shape[0]
    num_rows = U.shape[0]
    result = np.zeros (num_rows)
    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i],v)
        return result
    


In [33]:
matrix_vector_multiplication(U,v)

IndexError: tuple index out of range

In [34]:
U.dot(v)

array([20. ,  6. ,  8.5])

In [35]:
#MATRIX MATRIX MULTIPLICATION
V = np.array([
    [1,1,2],
    [1,2,1],
    [3,1,2]
])
V

array([[1, 1, 2],
       [1, 2, 1],
       [3, 1, 2]])

In [39]:
def matrix_matrix_multiplication (U,V):
 assert U.shape[1] == V.shape[0]
    num_rows = U.shape[0]
     num_cols = V.shape[1]
    result = np.zeros ((num_rows, num_cols))
    for i in range(num_cols):
        vi = V[:, i]
        Uvi= matrix_vector_multiplication(U, vi)
        result[:,i] = Uvi
        return result

IndentationError: unexpected indent (1734530103.py, line 3)

In [37]:
matrix_matrix_multiplication(U,V)

NameError: name 'matrix_matrix_multiplication' is not defined

In [40]:
U.dot(V)

ValueError: shapes (3,4) and (3,3) not aligned: 4 (dim 1) != 3 (dim 0)

In [42]:
#Identity Matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [43]:
V.dot(I)

NameError: name 'I' is not defined

In [45]:
#Inverse
Vs = V[[0,1,2]]
Vs

array([[1, 1, 2],
       [1, 2, 1],
       [3, 1, 2]])

In [46]:
Vs_inv = np.linalg.inv(Vs)
Vs_inv

array([[-5.00000000e-01,  3.70074342e-17,  5.00000000e-01],
       [-1.66666667e-01,  6.66666667e-01, -1.66666667e-01],
       [ 8.33333333e-01, -3.33333333e-01, -1.66666667e-01]])

In [47]:
Vs_inv.dot(Vs)

array([[ 1.00000000e+00,  5.55111512e-17,  0.00000000e+00],
       [ 0.00000000e+00,  1.00000000e+00, -5.55111512e-17],
       [ 2.77555756e-17, -2.77555756e-17,  1.00000000e+00]])