In [1]:
import numpy as np

In [2]:
np

<module 'numpy' from '/home/codespace/.local/lib/python3.12/site-packages/numpy/__init__.py'>

In [3]:
#Creating Arrays with Zeros, Ones, or Constants
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [7]:
# arrays
np.full(10,2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [8]:
#Python lists
[1, 2, 3, 4, 5]

[1, 2, 3, 4, 5]

In [13]:
#array lists
a = np.array([1, 2, 3, 4, 5])
a

array([1, 2, 3, 4, 5])

In [14]:
#if we want to access element 3
a [3]

np.int64(4)

In [15]:
#change to different
a [2] = 10
a

array([ 1,  2, 10,  4,  5])

In [16]:
#create range from 0 to 1
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
#arrey that filters number between first and
np.linspace(0,1,11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [18]:
#MULTI-DEMANTIONAL ARRAYS
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [19]:
np.array ([
          [1,2,3],
          [4,5,6],
          [7,8,9]
])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
#to access elements of those arreys
n = np.array ([
          [1,2,3],
          [4,5,6],
          [7,8,9]
])

In [22]:
#Change element
n[0,1]= 20
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [23]:
#get row 0
n[0]

array([ 1, 20,  3])

In [24]:
#change multiple rows
n[2]=[1,1,1]
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [25]:
#for column
n[:,1]

array([20,  5,  1])

In [27]:
#return all the rows
n[:]

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [28]:
#change columns
n[:,2]= [0,1,2]
n

array([[ 1, 20,  0],
       [ 4,  5,  1],
       [ 1,  1,  2]])

In [30]:
#RANDOMLY GENERATED ARRAYS
np.random.rand(5,2)

array([[0.9953784 , 0.57385056],
       [0.76699163, 0.3286242 ],
       [0.76077739, 0.63438545],
       [0.31309349, 0.54641241],
       [0.06808983, 0.48481053]])

In [31]:
#set up so the numbers do not change everytime you run code
np.random.seed(2)
np.random.rand(5,2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [32]:
#standard normal distribution
np.random.seed(2)
np.random.randn(5,2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [33]:
#for integer to have numbers multoply by 100
np.random.seed(2)
100 * np.random.randn(5,2)

array([[ -41.67578474,   -5.62668272],
       [-213.61960957,  164.02708084],
       [-179.34355852,  -84.17473657],
       [  50.28814172, -124.52880866],
       [-105.79522189,  -90.90076149]])

In [34]:
#randam integers generate, size 5 rows and 2 columns
np.random.seed(2)
np.random.randint(low = 0 ,high = 100, size=(5,2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

In [35]:
#ELEMENT WISE OPERATIONS
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [36]:
#add to all numbers 1
a + 1

array([1, 2, 3, 4, 5])

In [37]:
a * 2

array([0, 2, 4, 6, 8])

In [41]:
b = (a / 100)+10
b

array([10.  , 10.01, 10.02, 10.03, 10.04])

In [42]:
a + b

array([10.  , 11.01, 12.02, 13.03, 14.04])

In [43]:
#COMPARATION
a >= 2

array([False, False,  True,  True,  True])

In [44]:
a > b

array([False, False, False, False, False])

In [46]:
# which elenments a are greater than 
a[a < b]

array([0, 1, 2, 3, 4])

In [48]:
#SUMMARIZING OPERATION
#return smallest numbr
a.min()

np.int64(0)

In [49]:
a.max()

np.int64(4)

In [50]:
a.sum()

np.int64(10)

In [51]:
#average
a.mean()

np.float64(2.0)

In [52]:
n.min()

np.int64(0)